name: Notify Desktop (tag + Steam)

on:
  push:
    tags: [ "v*.*.*" ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build (e.g., v1.0.0)'
        required: false
        type: string

permissions:
  contents: read

jobs:
  notify:
    runs-on: ubuntu-22.04
    steps:
      - name: Notify desktop repo (steam release)
        env:
          GH_TOKEN: ${{ secrets.DESKTOP_REPO_TOKEN }}
          TAG: ${{ inputs.tag || github.ref_name }}
        run: |
          curl -f -X POST \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/sixarata/desktop/dispatches \
            -d '{"event_type":"steam_release","client_payload":{"repo":"sixarata/sixarata","ref":"'"$TAG"'"}}'